### ISSUE TITLE
Creating of the product vision draft

### ISSUE THREAD

**Issue by IwanHoogenboom** [ProgrammingLife2017/ProgrammingLife#12]
From the guidelines:

Who is going to buy the product? Who is the target customer? 
Which customer needs will the product address? 
Which product attributes are crucial to satisfy the selected needs, and therefore to the success of the product? 
How does the product compare against existing products, both from competitors and the same company? What are the product’s unique selling points? 
What is the target timeframe and budget to develop and launch the product?

https://docs.google.com/document/d/19J8In7yXjVMQPCNsysOrMUZcK1h6n60V37eOJP-xMWE/pub

**Comment by MeAmAnUsername** [comment]
@mvanmeerten is editor / has the final responsibility

The way I view this:
This week
 - @mvanmeerten and @IwanHoogenboom create a draft
 - everyone checks to see whether they agree with that description of our vision
 - @mvanmeerten and @IwanHoogenboom finish the document
 - we hand in the draft

next week
 - we get feedback
 - someone (to be decided for next sprint) finishes the document
