### ISSUE TITLE
Creating product planning draft

### ISSUE THREAD

**Issue by IwanHoogenboom** [ProgrammingLife2017/ProgrammingLife#13]
Refer the the guidelines:
https://docs.google.com/document/d/19J8In7yXjVMQPCNsysOrMUZcK1h6n60V37eOJP-xMWE/pub

**Comment by MeAmAnUsername** [comment]
@YDutchy is editor / has the final responsibility

The way I view this:
This week
 - @mvanmeerten and @YDutchy create a draft
 - everyone checks to see whether they agree with that description of our planning
 - @mvanmeerten and @YDutchy finish the document
 - we hand in the draft

next week
 - we get feedback
 - someone (to be decided for next sprint) finishes the document
